apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-acr-workspace
  title: 'Azure Container Registry plugin for Backstage'
  description: A Backstage plugin that displays information about your container images available in the Azure Container Registry
spec:
  lifecycle: experimental
  type: backstage-plugin
  owner: maintainers
