app:
  title: npm plugin example app
  baseUrl: http://localhost:3000

  extensions:
    - api:app/app-language:
        config:
          availableLanguages: ['en', 'de', 'es']
          defaultLanguage: 'en'

organization:
  name: npm plugin example

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    client: better-sqlite3
    connection: ':memory:'
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Plugin itself for techdocs
    - type: file
      target: ../../catalog-info.yaml
    - type: file
      target: ../../plugins/npm/catalog-info.yaml
    - type: file
      target: ../../plugins/npm-backend/catalog-info.yaml
    - type: file
      target: ../../plugins/npm-common/catalog-info.yaml
    # Local example data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]
    - type: file
      target: ../../examples/system.yaml
    - type: file
      target: ../../examples/npmjs-examples.yaml
    - type: file
      target: ../../examples/github-examples.yaml
    - type: file
      target: ../../examples/gitlab-examples.yaml
    - type: file
      target: ../../examples/failing-examples.yaml

    ## Uncomment these lines to add more example data
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

    ## Uncomment these lines to add an example org
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
    #   rules:
    #     - allow: [User, Group]

npm:
  defaultRegistry: npmjs
  registries:
    - name: npmjs
      url: https://registry.npmjs.com
    - name: github
      url: https://npm.pkg.github.com
    - name: gitlab
      url: https://gitlab.com/api/v4/packages/npm
    - name: gitlab-private
      url: https://gitlab.com/api/v4/packages/npm
      extraRequestHeaders:
        PRIVATE-TOKEN: ${NPM_PRIVATE_GITLAB_TOKEN}

# see https://backstage.io/docs/permissions/getting-started for more on the permission framework
permission:
  # setting this to `false` will disable permissions
  enabled: true
