apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-npm-workspace
  title: 'Backstage Community Npm Plugin'
  description: A Backstage plugin that shows meta info and latest versions from a npm registry
spec:
  lifecycle: experimental
  type: backstage-plugin
  owner: maintainers
