#!/usr/bin/env bash
# Export dev harness environment variables derived from the Keycloak realm fixture.
#
# Usage (from workspaces/keycloak):
#   eval "$(./scripts/export-dev-env-from-realm.sh)"
#
# The script also writes .env.dev.local (gitignored). In another terminal:
#   set -a && source .env.dev.local && set +a
#
# Optional overrides (export before running):
#   KEYCLOAK_BASE_URL          default: http://localhost:8080
#   KEYCLOAK_CLIENT_ID         default: backstage
#   BACKSTAGE_DEV_STATIC_TOKEN generated from the realm fixture when unset
#   AUTH_SESSION_SECRET        default: dev-auth-session-secret
#   DEV_ENV_FILE               default: .env.dev.local (workspace root)
#
# Flags:
#   --stdout-only   print exports only; do not write DEV_ENV_FILE
#
# Requires: jq, shasum or sha256sum

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
REALM_JSON="${REALM_JSON:-${WORKSPACE_ROOT}/plugins/catalog-backend-module-keycloak/__fixtures__/keycloak-realm.json}"
DEV_ENV_FILE="${DEV_ENV_FILE:-${WORKSPACE_ROOT}/.env.dev.local}"
STDOUT_ONLY=false

for arg in "$@"; do
  case "${arg}" in
    --stdout-only)
      STDOUT_ONLY=true
      ;;
    -h | --help)
      sed -n '2,/^$/p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *)
      echo "export-dev-env-from-realm.sh: unknown argument: ${arg}" >&2
      exit 1
      ;;
  esac
done

if ! command -v jq >/dev/null 2>&1; then
  echo "export-dev-env-from-realm.sh: jq is required" >&2
  exit 1
fi

sha256_digest() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256
  elif command -v sha256sum >/dev/null 2>&1; then
    sha256sum
  else
    echo "export-dev-env-from-realm.sh: shasum or sha256sum is required" >&2
    exit 1
  fi
}

if [[ ! -f "${REALM_JSON}" ]]; then
  echo "export-dev-env-from-realm.sh: realm fixture not found at ${REALM_JSON}" >&2
  exit 1
fi

KEYCLOAK_BASE_URL="${KEYCLOAK_BASE_URL:-http://localhost:8080}"
KEYCLOAK_CLIENT_ID="${KEYCLOAK_CLIENT_ID:-backstage}"
AUTH_SESSION_SECRET="${AUTH_SESSION_SECRET:-dev-auth-session-secret}"

KEYCLOAK_REALM="$(jq -r '.realm' "${REALM_JSON}")"
KEYCLOAK_CLIENT_SECRET="$(jq -r --arg clientId "${KEYCLOAK_CLIENT_ID}" '
  .clients[]
  | select(.clientId == $clientId)
  | .secret
' "${REALM_JSON}")"

if [[ -z "${KEYCLOAK_REALM}" || "${KEYCLOAK_REALM}" == "null" ]]; then
  echo "export-dev-env-from-realm.sh: missing .realm in ${REALM_JSON}" >&2
  exit 1
fi

if [[ -z "${KEYCLOAK_CLIENT_SECRET}" || "${KEYCLOAK_CLIENT_SECRET}" == "null" ]]; then
  echo "export-dev-env-from-realm.sh: no secret for client \"${KEYCLOAK_CLIENT_ID}\" in ${REALM_JSON}" >&2
  exit 1
fi

if [[ -z "${BACKSTAGE_DEV_STATIC_TOKEN:-}" ]]; then
  BACKSTAGE_DEV_STATIC_TOKEN="$(
    printf '%s:%s:%s' "${KEYCLOAK_REALM}" "${KEYCLOAK_CLIENT_ID}" "${KEYCLOAK_CLIENT_SECRET}" \
      | sha256_digest \
      | awk '{print $1}'
  )"
fi

write_env_exports() {
  cat <<EOF
export KEYCLOAK_BASE_URL='${KEYCLOAK_BASE_URL}'
export KEYCLOAK_REALM='${KEYCLOAK_REALM}'
export KEYCLOAK_CLIENT_ID='${KEYCLOAK_CLIENT_ID}'
export KEYCLOAK_CLIENT_SECRET='${KEYCLOAK_CLIENT_SECRET}'
export AUTH_KEYCLOAK_BASE_URL='${KEYCLOAK_BASE_URL}'
export AUTH_KEYCLOAK_REALM='${KEYCLOAK_REALM}'
export AUTH_KEYCLOAK_CLIENT_ID='${KEYCLOAK_CLIENT_ID}'
export AUTH_KEYCLOAK_CLIENT_SECRET='${KEYCLOAK_CLIENT_SECRET}'
export BACKSTAGE_DEV_STATIC_TOKEN='${BACKSTAGE_DEV_STATIC_TOKEN}'
export AUTH_SESSION_SECRET='${AUTH_SESSION_SECRET}'
EOF
}

if [[ "${STDOUT_ONLY}" == false ]]; then
  {
    echo "# Generated by scripts/export-dev-env-from-realm.sh — do not commit."
    echo "# Re-run after realm fixture or override env changes."
    write_env_exports
  } >"${DEV_ENV_FILE}"
  echo "export-dev-env-from-realm.sh: wrote ${DEV_ENV_FILE} — other shells: set -a && source ${DEV_ENV_FILE} && set +a" >&2
fi

echo "export-dev-env-from-realm.sh: run eval in this shell, then start the dev harness (env vars must be set before backend startup)." >&2

write_env_exports
