---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-catalog-model
  annotations:
    npm/package: '@backstage/catalog-model'
    npm/show-tags: latest, next
spec:
  type: library
  lifecycle: production
  owner: guests
  system: backstage
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-catalog-client
  annotations:
    npm/package: '@backstage/catalog-client'
    npm/show-tags: latest, next
spec:
  type: library
  lifecycle: production
  owner: guests
  system: backstage
  dependsOn:
    - component:backstage-catalog-model
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-catalog-common
  annotations:
    npm/package: '@backstage/plugin-catalog-common'
    npm/show-tags: latest, next
spec:
  type: library
  lifecycle: production
  owner: guests
  system: backstage
  dependsOn:
    - component:backstage-catalog-model
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-catalog-node
  annotations:
    npm/package: '@backstage/plugin-catalog-node'
    npm/show-tags: latest, next
spec:
  type: library
  lifecycle: production
  owner: guests
  system: backstage
  dependsOn:
    - component:backstage-catalog-model
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-catalog-react
  annotations:
    npm/package: '@backstage/plugin-catalog-react'
    npm/show-tags: latest, next
spec:
  type: library
  lifecycle: production
  owner: guests
  system: backstage
  dependsOn:
    - component:backstage-catalog-model
    - component:backstage-catalog-client
    - component:backstage-plugin-catalog-common
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-catalog
  annotations:
    npm/package: '@backstage/plugin-catalog'
    npm/show-tags: latest, next
spec:
  type: website
  lifecycle: production
  owner: guests
  system: backstage
  dependsOn:
    - component:backstage-catalog-model
    - component:backstage-catalog-client
    - component:backstage-plugin-catalog-common
    - component:backstage-plugin-catalog-react
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-catalog-backend
  annotations:
    npm/package: '@backstage/plugin-catalog-backend'
spec:
  type: service
  lifecycle: production
  owner: guests
  system: backstage
  dependsOn:
    - component:backstage-catalog-model
    - component:backstage-catalog-client
    - component:backstage-plugin-catalog-common
    - component:backstage-plugin-catalog-node
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: npm-package-not-found
  annotations:
    npm/package: npm-package-not-found
spec:
  type: service
  lifecycle: testing
  owner: guests
  system: backstage
