---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-ui
  annotations:
    npm/package: '@backstage/ui'
    npm/show-tags: latest, next
spec:
  type: library
  lifecycle: production
  owner: backstage
  system: backstage
