compressionLevel: mixed

enableGlobalCache: true

httpTimeout: 300000

nodeLinker: node-modules
nmMode: hardlinks-local

npmRegistryServer: 'https://registry.npmjs.org/'

yarnPath: .yarn/releases/yarn-4.7.0.cjs
