approvedGitRepositories:
  - '**'

compressionLevel: mixed

enableGlobalCache: true

enableScripts: true

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

packageExtensions:
  '@backstage/cli-module-test-jest@*':
    dependencies:
      jest-cli: ^29.7.0
      jest-environment-node: ^29.7.0
      jest-runtime: ^29.7.0
      yaml: ^2.8.1

plugins:
  - checksum: e036bbabee4fda5a34aed96597e1fa22a0fc753bc7737c525c1b7e37d626f4894e71a01fe7440458a3d034b7f9e648c394cebfb3b47a75b731b16e5b8d50fe60
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: 'https://versions.backstage.io/v1/releases/1.55.1/yarn-plugin'
