approvedGitRepositories:
  - '**'

compressionLevel: mixed

enableGlobalCache: true

enableScripts: true

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

packageExtensions:
  '@backstage/cli-module-test-jest@*':
    dependencies:
      jest-cli: ^29.7.0
      jest-environment-node: ^29.7.0
      jest-runtime: ^29.7.0
      yaml: ^2.8.1

plugins:
  - checksum: 0cfdc882d3c1395592aa6d4690958e70ebbc3a8ee1d888d523dc9e3c74796de26f744c37df66a69212280634f422a88074ba625dce0f7886fbdf2a904a0c38a2
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: 'https://versions.backstage.io/v1/releases/1.52.0/yarn-plugin'
