approvedGitRepositories:
  - '**'

compressionLevel: mixed

enableGlobalCache: true

enableScripts: true

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

packageExtensions:
  '@backstage/cli-module-test-jest@*':
    dependencies:
      jest-cli: ^29.7.0
      jest-environment-node: ^29.7.0
      jest-runtime: ^29.7.0
      yaml: ^2.8.1

plugins:
  - checksum: a6895be0b30a75db6fddafedff143f82ccbd74656bad97775c6a0b9eba6e6ea6b7d66a8e9d0c8505755a981e86b7c6c1c9334ead299a857cf8d6e243957b0bab
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: 'https://versions.backstage.io/v1/releases/1.50.2/yarn-plugin'
