import fs from 'fs';
import path from 'path';
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const docsDir = path.join(__dirname, 'docs');

const workspaces = fs
  .readdirSync(docsDir, { withFileTypes: true })
  .filter(dir => dir.isDirectory() && dir.name !== 'home')
  .map(dir => dir.name);

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Home',
      collapsible: false,
      collapsed: false,
      link: { type: 'doc', id: 'home/index' },
      items: [],
    },
    ...workspaces.map(workspace => ({
      type: 'category',
      label: workspace,
      items: [{ type: 'autogenerated', dirName: workspace }],
    })),
  ],
};

export default sidebars;
