apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-scaffolder-sonarqube
  title: SonarQube scaffolder actions
  description: This module provides Backstage template actions for SonarQube.
  tags:
    - scaffolder
spec:
  type: backstage-plugin
  lifecycle: production
  owner: rhdh-team
