apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shorturl
  description: An example of a Backstage application.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental