# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-ocm
  title: OCM plugin
  description: Open Cluster Management plugin for Backstage
  annotations:
    github.com/project-slug: backstage-community/backstage-plugins
  tags:
    - kubernetes
    - openshift
  links:
    - url: https://github.com/backstage/community-plugins/tree/main/workspaces/ocm/plugins/ocm
      title: GitHub Source
      icon: source
      type: source
spec:
  type: backstage-plugin
  lifecycle: production
  owner: rhdh-team
