name: 🐛 Plugin Bug Report
description: Submit a plugin bug report to help us improve
title: '🐛 <Plugin>: <Title>'
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: We value your time and effort to submit this bug report. 🙏
  - type: dropdown
    id: workspace
    attributes:
      label: Workspace
      options:
        - 3scale
        - acr
        - adr
        - airbrake
        - allure
        - analytics
        - announcements
        - apache-airflow
        - apollo-explorer
        - azure-devops
        - azure-sites
        - azure-storage-explorer
        - badges
        - bazaar
        - bitrise
        - blackduck
        - cicd-statistics
        - cloudbuild
        - code-climate
        - code-coverage
        - codescene
        - confluence
        - copilot
        - cost-insights
        - dynatrace
        - entity-feedback
        - entity-validation
        - explore
        - feedback
        - firehydrant
        - fossa
        - gcalendar
        - gcp-projects
        - git-release-manager
        - github-actions
        - github-deployments
        - github-issues
        - github-pull-requests-board
        - gitops-profiles
        - gocd
        - grafana
        - graphiql
        - graphql-voyager
        - ilert
        - jaeger
        - jenkins
        - jfrog-artifactory
        - kafka
        - keycloak
        - kiali
        - lighthouse
        - linguist
        - linkerd
        - matomo
        - mend
        - microsoft-calendar
        - mta
        - newrelic
        - nexus-repository-manager
        - nomad
        - npm
        - ocm
        - octopus-deploy
        - odo
        - opencost
        - periskop
        - pingidentity
        - playlist
        - puppetdb
        - quay
        - rbac
        - redhat-argocd
        - redhat-resource-optimization
        - report-portal
        - rollbar
        - scaffolder-backend-module-annotator
        - scaffolder-backend-module-kubernetes
        - scaffolder-backend-module-regex
        - scaffolder-backend-module-servicenow
        - scaffolder-backend-module-sonarqube
        - scaffolder-relation-processor
        - sentry
        - shortcuts
        - sonarqube
        - splunk
        - stack-overflow
        - stackstorm
        - tech-insights
        - tech-radar
        - tekton
        - todo
        - topology
        - vault
        - xcmetrics
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: 📜 Description
      description: A clear and concise description of what the bug is.
      placeholder: It bugs out when ...
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: 👍 Expected behavior
      description: What did you think should happen?
      placeholder: It should ...
  - type: textarea
    id: actual-behavior
    validations:
      required: true
    attributes:
      label: 👎 Actual Behavior with Screenshots
      description: What did actually happen? Add screenshots, if applicable.
      placeholder: It actually ...
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: 👟 Reproduction steps
      description: How do you trigger this bug? Please walk us through it step by step.
      placeholder: >-
        Provide a link to a live example, or an unambiguous set of steps to
        reproduce this bug. Include code or configuration to reproduce, if
        relevant.
         1. Go to '...'
         2. Click on '....'
         3. Scroll down to '....'
  - type: textarea
    id: context
    validations:
      required: false
    attributes:
      label: 📃 Provide the context for the Bug.
      description: How has this issue affected you? What are you trying to accomplish?
      placeholder: >-
        Providing context (e.g. links to configuration settings, stack trace or
        log data) helps us come up with a solution that is most useful in the
        real world.
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: 👀 Have you spent some time to check if this bug has been raised before?
      options:
        - label: I checked and didn't find similar issue
          required: true
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: 🏢 Have you read the Code of Conduct?
      options:
        - label: >-
            I have read the [Code of
            Conduct](https://github.com/backstage/community-plugins/blob/main/CODE_OF_CONDUCT.md)
          required: true
  - type: dropdown
    attributes:
      label: Are you willing to submit PR?
      description: >-
        This is absolutely not required, but we are happy to guide you in the
        contribution process.
      options:
        - Yes I am willing to submit a PR!
        - No, but I'm happy to collaborate on a PR with someone else
        - No, I don't have time to work on this right now
