name: 🚀 Plugin Feature
description: Submit a proposal for a new feature in a plugin
title: '🚀 <Plugin>: <Title>'
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        We value your time and efforts to submit this Feature request form. 🙏
  - type: dropdown
    id: workspace
    attributes:
      label: Workspace
      options:
        - 3scale
        - acr
        - adr
        - airbrake
        - allure
        - analytics
        - announcements
        - apache-airflow
        - apollo-explorer
        - azure-devops
        - azure-sites
        - azure-storage-explorer
        - badges
        - bazaar
        - bitrise
        - blackduck
        - cicd-statistics
        - cloudbuild
        - code-climate
        - code-coverage
        - codescene
        - confluence
        - copilot
        - cost-insights
        - dynatrace
        - entity-feedback
        - entity-validation
        - explore
        - feedback
        - firehydrant
        - fossa
        - gcalendar
        - gcp-projects
        - git-release-manager
        - github-actions
        - github-deployments
        - github-issues
        - github-pull-requests-board
        - gitops-profiles
        - gocd
        - grafana
        - graphiql
        - graphql-voyager
        - ilert
        - jaeger
        - jenkins
        - jfrog-artifactory
        - kafka
        - keycloak
        - kiali
        - lighthouse
        - linguist
        - linkerd
        - matomo
        - mend
        - microsoft-calendar
        - mta
        - newrelic
        - nexus-repository-manager
        - nomad
        - npm
        - ocm
        - octopus-deploy
        - odo
        - opencost
        - periskop
        - pingidentity
        - playlist
        - puppetdb
        - quay
        - rbac
        - redhat-argocd
        - redhat-resource-optimization
        - report-portal
        - rollbar
        - scaffolder-backend-module-annotator
        - scaffolder-backend-module-kubernetes
        - scaffolder-backend-module-regex
        - scaffolder-backend-module-servicenow
        - scaffolder-backend-module-sonarqube
        - scaffolder-relation-processor
        - sentry
        - shortcuts
        - sonarqube
        - splunk
        - stack-overflow
        - stackstorm
        - tech-insights
        - tech-radar
        - tekton
        - todo
        - topology
        - vault
        - xcmetrics
      default: 0
    validations:
      required: true
  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: 🔖 Feature description
      description: A clear and concise description of what the feature is.
      placeholder: You should add ...
  - type: textarea
    id: context
    validations:
      required: true
    attributes:
      label: 🎤 Context
      description: >-
        Please explain why this feature should be implemented and how it would
        be used. Add examples, if applicable.
      placeholder: In my use-case, ...
  - type: textarea
    id: implementation
    attributes:
      label: ✌️ Possible Implementation
      description: A clear and concise description of what you want to happen.
      placeholder: >-
        Not obligatory, but ideas as to the implementation of the addition or
        change
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: >-
        👀 Have you spent some time to check if this feature request has been
        raised before?
      options:
        - label: I checked and didn't find similar issue
          required: true
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: 🏢 Have you read the Code of Conduct?
      options:
        - label: >-
            I have read the [Code of
            Conduct](https://github.com/backstage/community-plugins/blob/main/CODE_OF_CONDUCT.md)
          required: true
  - type: dropdown
    id: willing-to-submit-pr
    attributes:
      label: Are you willing to submit PR?
      description: >-
        This is absolutely not required, but we are happy to guide you in the
        contribution process.
      options:
        - Yes I am willing to submit a PR!
        - No, but I'm happy to collaborate on a PR with someone else
        - No, I don't have time to work on this right now
