---
blank_issues_enabled: false
contact_links:
  - about: "Use the Backstage Community Discord for questions & discussions"
    name: Questions
    url: "https://discord.gg/backstage-687207715902193673"
