apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: redhat-argocd
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   argocd/app-selector: app.kubernetes.io/instance=rhtap-nodeapp

spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
