---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: runtime-platform
spec:
  owner: team-a 
  system: software-deployment
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: software-deployment
spec:
  owner: team-a 
  domain: runtime
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ci-runner
spec:
  type: service
  owner: team-a 
  system: software-deployment
