---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: cruz
spec:
  memberOf: [family]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: christina
spec:
  memberOf: [family]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: family
spec:
  type: team
  children: []
---

