apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pingidentity
  title: '@backstage-community/pingidentity'
  description: An Backstage plugin that ingests users and groups from Ping Identity into the catalog.
spec:
  type: backstage-backend-plugin-module
  owner: jessicajhee
  lifecycle: experimental
