apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  description: Guest users
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
