type: dropdown
id: workspace
attributes:
  label: Workspace
  options:
    - 3scale
    - acr
    - adr
    - airbrake
    - allure
    - analytics
    - announcements
    - apache-airflow
    - apollo-explorer
    - azure-devops
    - azure-resources
    - azure-sites
    - azure-storage-explorer
    - badges
    - bazaar
    - bitrise
    - blackduck
    - cicd-statistics
    - cloudbuild
    - code-climate
    - code-coverage
    - codescene
    - confluence
    - copilot
    - cost-insights
    - dynatrace
    - entity-feedback
    - entity-validation
    - explore
    - feedback
    - firehydrant
    - fossa
    - gcalendar
    - gcp-projects
    - git-release-manager
    - github-actions
    - github-deployments
    - github-discussions
    - github-issues
    - github-pull-requests-board
    - gitops-profiles
    - gocd
    - grafana
    - graphiql
    - graphql-voyager
    - ilert
    - jaeger
    - jenkins
    - jfrog-artifactory
    - kafka
    - keycloak
    - kiali
    - lighthouse
    - linguist
    - linkerd
    - matomo
    - mend
    - microsoft-calendar
    - mta
    - newrelic
    - nexus-repository-manager
    - nomad
    - npm
    - ocm
    - octopus-deploy
    - odo
    - opencost
    - periskop
    - pingidentity
    - playlist
    - puppetdb
    - quay
    - rbac
    - redhat-argocd
    - redhat-resource-optimization
    - report-portal
    - rollbar
    - scaffolder-backend-module-annotator
    - scaffolder-backend-module-kubernetes
    - scaffolder-backend-module-regex
    - scaffolder-backend-module-servicenow
    - scaffolder-backend-module-sonarqube
    - scaffolder-relation-processor
    - sentry
    - shortcuts
    - sonarqube
    - splunk
    - stack-overflow
    - stackstorm
    - tech-insights
    - tech-radar
    - tekton
    - todo
    - topology
    - vault
    - xcmetrics
  default: 0
validations:
  required: true
