/*
 * Copyright 2024 The Backstage Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1LocalObjectReference } from './V1LocalObjectReference';

/**
 * Represents a cloud-init nocloud user data source. More info: http://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html
 * @export
 * @interface V1CloudInitNoCloudSource
 */
export interface V1CloudInitNoCloudSource {
  /**
   * NetworkData contains NoCloud inline cloud-init networkdata. + optional
   * @type {string}
   * @memberof V1CloudInitNoCloudSource
   */
  networkData?: string;
  /**
   * NetworkDataBase64 contains NoCloud cloud-init networkdata as a base64 encoded string. + optional
   * @type {string}
   * @memberof V1CloudInitNoCloudSource
   */
  networkDataBase64?: string;
  /**
   *
   * @type {V1LocalObjectReference}
   * @memberof V1CloudInitNoCloudSource
   */
  networkDataSecretRef?: V1LocalObjectReference;
  /**
   *
   * @type {V1LocalObjectReference}
   * @memberof V1CloudInitNoCloudSource
   */
  secretRef?: V1LocalObjectReference;
  /**
   * UserData contains NoCloud inline cloud-init userdata. + optional
   * @type {string}
   * @memberof V1CloudInitNoCloudSource
   */
  userData?: string;
  /**
   * UserDataBase64 contains NoCloud cloud-init userdata as a base64 encoded string. + optional
   * @type {string}
   * @memberof V1CloudInitNoCloudSource
   */
  userDataBase64?: string;
}
