/*
 * Copyright 2024 The Backstage Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1DiskTarget
 */
export interface V1DiskTarget {
  /**
   * Bus indicates the type of disk device to emulate. supported values: virtio, sata, scsi.
   * @type {string}
   * @memberof V1DiskTarget
   */
  bus?: string;
  /**
   * If specified, the virtual disk will be placed on the guests pci address with the specifed PCI address. For example: 0000:81:01.10 +optional
   * @type {string}
   * @memberof V1DiskTarget
   */
  pciAddress?: string;
  /**
   * ReadOnly. Defaults to false.
   * @type {boolean}
   * @memberof V1DiskTarget
   */
  readonly?: boolean;
}
