/*
 * Copyright 2024 The Backstage Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a disk created on the cluster level
 * @export
 * @interface V1HostDisk
 */
export interface V1HostDisk {
  /**
   * Capacity of the sparse disk +optional
   * @type {string}
   * @memberof V1HostDisk
   */
  capacity?: string;
  /**
   * The path to HostDisk image located on the cluster
   * @type {string}
   * @memberof V1HostDisk
   */
  path: string;
  /**
   * Shared indicate whether the path is shared between nodes
   * @type {boolean}
   * @memberof V1HostDisk
   */
  shared?: boolean;
  /**
   * Contains information if disk.img exists or should be created allowed options are \'Disk\' and \'DiskOrCreate\'
   * @type {string}
   * @memberof V1HostDisk
   */
  type: string;
}
