apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: new-salesforce-crm
  namespace: default
spec:
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Repos
  namespace: default
spec:
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: audio-playback
  namespace: default
spec:
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: podcast
  namespace: default
spec:
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: artist-engagement-portal
  namespace: default
spec:
  owner: guests
