/*
 * Copyright 2024 The Backstage Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import {
  Entity,
  getCompoundEntityRef,
  parseEntityRef,
  stringifyEntityRef,
} from '@backstage/catalog-model';
import type { LocationSpec } from '@backstage/plugin-catalog-common';
import {
  CatalogProcessor,
  CatalogProcessorCache,
  CatalogProcessorEmit,
  processingResult,
} from '@backstage/plugin-catalog-node';
import type { EventsService } from '@backstage/plugin-events-node';

import { RELATION_SCAFFOLDED_FROM, RELATION_SCAFFOLDER_OF } from './relations';
import type { ScaffoldedFromSpec } from './types';
import { handleTemplateVersion } from './templateVersionUtils';

/** @public */
export class ScaffolderRelationEntityProcessor implements CatalogProcessor {
  constructor(private readonly eventsService?: EventsService) {}

  getProcessorName(): string {
    return 'ScaffolderRelationEntityProcessor';
  }

  async preProcessEntity(
    entity: Entity,
    _location: LocationSpec,
    _emit: CatalogProcessorEmit,
    _originLocation: LocationSpec,
    cache: CatalogProcessorCache,
  ): Promise<Entity> {
    if (entity.kind !== 'Template') {
      return entity;
    }

    const currentVersion =
      entity.metadata.annotations?.['backstage.io/template-version'];
    if (!currentVersion) {
      return entity;
    }

    const entityRef = stringifyEntityRef(entity);

    await handleTemplateVersion(
      entityRef,
      currentVersion,
      cache,
      this.eventsService,
    );

    return entity;
  }

  async postProcessEntity(
    entity: Entity,
    _location: LocationSpec,
    emit: CatalogProcessorEmit,
  ): Promise<Entity> {
    const selfRef = getCompoundEntityRef(entity);

    /**
     * Utilities
     */
    function doEmit(
      targets: string | string[] | undefined,
      context: { defaultKind?: string; defaultNamespace: string },
      outgoingRelation: string,
      incomingRelation: string,
    ): void {
      if (!targets) {
        return;
      }
      for (const target of [targets].flat()) {
        const targetRef = parseEntityRef(target, context);
        emit(
          processingResult.relation({
            source: selfRef,
            type: outgoingRelation,
            target: {
              kind: targetRef.kind,
              namespace: targetRef.namespace,
              name: targetRef.name,
            },
          }),
        );
        emit(
          processingResult.relation({
            source: {
              kind: targetRef.kind,
              namespace: targetRef.namespace,
              name: targetRef.name,
            },
            type: incomingRelation,
            target: selfRef,
          }),
        );
      }
    }

    /**
     * Emit relations for entities generated by templates (can be any entity type)
     */
    const arbitraryEntity = entity as Entity & Partial<ScaffoldedFromSpec>;
    doEmit(
      arbitraryEntity.spec?.scaffoldedFrom,
      { defaultKind: 'Template', defaultNamespace: selfRef.namespace },
      RELATION_SCAFFOLDED_FROM,
      RELATION_SCAFFOLDER_OF,
    );
    return entity;
  }
}
