app:
  title: Quay Example App
  baseUrl: http://localhost:3000
  experimental:
    packages: 'all'
  extensions:
    - entity-card:catalog/about
    - entity-card:catalog/labels
    - entity-card:catalog/links:
        config:
          filter: kind:component has:links

organization:
  name: Quay Example

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'

auth:
  providers:
    guest: {}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

    # Quay template
    - type: file
      target: ../../plugins/quay-actions/examples/templates/01-quay-template.yaml
      rules:
        - allow: [Template]

quay:
  apiUrl: 'https://quay.io'
  apiKey: ''
