app:
  title: Quay Example App
  baseUrl: http://localhost:3000
  experimental:
    packages: 'all'
  extensions:
    - app/routes:
        config:
          redirects:
            - from: /
              to: /catalog
    - entity-card:catalog/about
    - entity-card:catalog/labels
    - entity-card:catalog/links:
        config:
          filter: kind:component has:links

organization:
  name: Quay Example

auth:
  providers:
    guest: {}

backend:
  baseUrl: http://localhost:7007

quay:
  apiUrl: 'https://quay.io'
