# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-community-quay
  title: Quay plugin
  description: Quay plugin for Backstage
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/quay/plugins/quay
    backstage.io/view-url: https://github.com/backstage/community-plugins/blob/main/workspaces/quay/plugins/quay/catalog-info.yaml
    backstage.io/edit-url: https://github.com/backstage/community-plugins/edit/main/workspaces/quay/plugins/quay/catalog-info.yaml
    github.com/project-slug: backstage-community/backstage-plugins
    github.com/team-slug: backstage-community/rhtap
    sonarqube.org/project-key: backstage-community_plugins
  tags:
    - quay
  links:
    - url: https://github.com/backstage/community-plugins/tree/main/workspaces/quay/plugins/quay
      title: GitHub Source
      icon: source
      type: source
spec:
  type: backstage-plugin
  lifecycle: production
  owner: rhtap-team
  system: backstage
  subcomponentOf: backstage-community-plugins
