# Contains entities used for local development
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-component
  description: Test component
spec:
  type: repository
  lifecycle: experimental
  owner: user:development/guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-component-2
  description: Test component 2
spec:
  type: repository
  lifecycle: experimental
  owner: user:development/john.doe
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest.user
  title: Guest User
  namespace: development
spec:
  memberOf:
    - group:default/test-group
  profile:
    displayName: Guest User
    email: foobar@foo.com
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: john.doe
  title: John Doe
  namespace: development
spec:
  memberOf:
    - group:default/test-group
  profile:
    displayName: John Doe
    email: barfoo@foo.com
