apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: report-portal-plugin
  description: An example report portal component.
  annotations:
    reportportal.io/launch-name: Demo Api Tests
    reportportal.io/project-name: dxp_qe
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: user:development/guest
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
  namespace: development
spec:
  profile:
    displayName: Guest
    email: guest@example.com
    picture: https://avatars.dicebear.com/api/initials/guest@example.com.svg
  memberOf: [guests]
