---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service
  annotations:
    backstage.io/kubernetes-id: example-service
    # backstage.io/kubernetes-namespace: example-namespace
    tekton.dev/cicd: 'true'
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: another-service-without-tekton
  annotations:
    backstage.io/kubernetes-id: example-service
    # backstage.io/kubernetes-namespace: example-namespace
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tekton-demo
  namespace: development
  annotations:
    tekton.dev/cicd: 'true'
    # It's important that your Tekton CRs have this annotation. If not they wont appear.
    backstage.io/kubernetes-id: 'rhtap'
    backstage.io/kubernetes-namespace: 'tekton-pipelines'
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
---