---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: [sub-guests]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sub-guests
spec:
  type: team
  children: [sub-sub-guests]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sub-sub-guests
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: employees
spec:
  type: team
  children:
    - developers
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: developers
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-corp
spec:
  type: team
  children:
    - untrusted
    - employees
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sub-guests
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: untrusted
spec:
  type: team
  children:
    - guests
