app:
  title: ArgoCD
  baseUrl: http://localhost:3000
  experimental:
    packages: 'all'
  extensions:
    - api:app/app-language:
        config:
          availableLanguages: ['en', 'de', 'es', 'fr', 'it', 'ja']
          defaultLanguage: 'en'
    - app/routes:
        config:
          redirects:
            - from: /
              to: /catalog
    - entity-card:catalog/about
    - entity-card:catalog/labels
    - entity-card:catalog/links:
        config:
          filter: kind:component has:links

organization:
  name: ArgoCD

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

auth:
  providers:
    guest: {}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    - type: file
      target: ../../examples/entities.yaml

    - type: file
      target: ../../examples/argocd-entities.yaml

    - type: file
      target: ../../examples/templates/argocd-create-resources.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/templates/argocd-find-applications.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/templates/argocd-get-application.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/templates/argocd-get-revision-details.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/templates/argocd-list-applications.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

argocd:
  appLocatorMethods:
    - type: 'config'
      instances:
        - name: main
          url: 'https://test-openshift-gitops.apps.test.devcluster.openshift.com'
          token: fake-jwt-token
        - name: argoInstance1
          url: 'https://test1-openshift-gitops.apps.test.devcluster.openshift.com'
          token: fake-jwt-token1
        - name: argoInstance2
          url: 'https://test2-openshift-gitops.apps.test.devcluster.openshift.com'
          token: fake-jwt-token2

permission:
  # setting this to `false` will disable permissions
  enabled: false
  rbac:
    pluginsWithPermission:
      - argocd
      - catalog
      - permission
      - scaffolder
    policies-csv-file: ../../examples/rbac-policies.csv
    admin:
      users:
        - name: user:development/guest
