app:
  title: Backstage Example App
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  csp:
    connect-src: ["'self'", 'http:', 'https:']

catalog:
  rules:
    - allow:
        - Component
        - API
        - Resource
        - System
        - Domain
        - Location

  locations:
    # Backstage example entities
    - type: file
      target: ./example-entities/all.yaml
    # Backstage example groups and users
    - type: file
      target: ./example-entities/acme-corp.yaml
      rules:
        - allow: [User, Group]

auth:
  environment: development
  providers:
    guest: {}

permission:
  enabled: true
