app:
  title: Analytics Dev App
  baseUrl: http://localhost:3000
  analytics:
    # Matomo analytics provider config
    matomo:
      host: ${MATOMO_HOST}
      siteId: ${MATOMO_SITE_ID}

    newRelic:
      # New Relic browser monitoring config
      endpoint: 'bam.nr-data.net'
      accountId: '1234567890'
      applicationId: '1234567890'
      licenseKey: '1234567890'
      distributedTracingEnabled: true
      cookiesEnabled: true
      sessionReplay:
        enabled: true
        samplingRate: 100
        errorSamplingRate: 100

    segment:
      # Segment analytics provider config
      writeKey: ${SEGMENT_WRITE_KEY}

backend:
  baseUrl: http://localhost:7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin:
      - http://localhost:3000
      - http://localhost:7007
      # for new relic browser monitoring
      - https://bam.nr-data.net
      - https://bam.eu01.nr-data.net
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  reading:
    allow:
      - host: localhost
