app:
  title: Analytics Dev App
  baseUrl: http://localhost:3000
  analytics:
    # Matomo analytics provider config
    matomo:
      host: ${MATOMO_HOST}
      siteId: ${MATOMO_SITE_ID}
    newRelic:
      # New Relic browser monitoring config
      endpoint: 'bam.nr-data.net'
      accountId: '1234567890'
      applicationId: '1234567890'
      licenseKey: '1234567890'
      distributedTracingEnabled: true
      cookiesEnabled: true
      sessionReplay:
        enabled: true
        samplingRate: 100
        errorSamplingRate: 100

backend:
  baseUrl: http://localhost:7007
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  reading:
    allow:
      - host: localhost
