name: Auto Version Bump

on:
  workflow_dispatch:

concurrency:
  group: auto-version-bump
  cancel-in-progress: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate workspace matrix
        id: set-matrix
        run: |
          matrix=$(node scripts/ci/generate-auto-bump-matrix.js)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  batch-dispatch:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Delay batches (5 min between)
        if: ${{ strategy.job-index != 0 }}
        run: |
          delay=$(( strategy.job-index * 300 ))
          echo "Sleeping $delay seconds before triggering batch ${{ strategy.job-index }}..."
          sleep $delay

      - name: Trigger Version Bump Workflow via GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Triggering version bump for batch ${{ strategy.job-index }}"
          gh workflow run version-bump.yml \
            --ref main \
            --field release_line=main \
            --field workspace_input="${{ toJson(matrix.batch) }}" \
            --field version-bump-type=minor
