name: PR Workspace Delegation

on:
  pull_request:
    paths:
      - "workspaces/**"

jobs:
  call-ci:
    runs-on: ubuntu-latest
    outputs:
      workspace: ${{ steps.detect-workspace.outputs.out }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: yarn install
      - name: Run workspace detection
        id: detect-workspace
        run: yarn run detect-workspace >> $GITHUB_OUTPUT
      - uses: backstage/community-plugins/.github/workflows/ci.yml@main
        with:
          workspace: ${{ steps.detect-workspace.outputs.out }}
